"""Generated from lexicons/manifest.toml; do not edit manually."""

from __future__ import annotations

GENERATED_LEXICONS = (
    {
        "id": "en-us:gold",
        "language": "en-us",
        "name": "gold",
        "resource": "en_us_gold.g2lex",
        "kind": "pronunciation",
        "rating": 4,
        "case_aliases": True,
        "phoneme_encoding": "kokoro-v1",
        "default_priority": 10,
    },
    {
        "id": "en-us:silver",
        "language": "en-us",
        "name": "silver",
        "resource": "en_us_silver.g2lex",
        "kind": "pronunciation",
        "rating": 3,
        "case_aliases": True,
        "phoneme_encoding": "kokoro-v1",
        "default_priority": 20,
    },
    {
        "id": "en-gb:gold",
        "language": "en-gb",
        "name": "gold",
        "resource": "en_gb_gold.g2lex",
        "kind": "pronunciation",
        "rating": 4,
        "case_aliases": True,
        "phoneme_encoding": "kokoro-v1",
        "default_priority": 10,
    },
    {
        "id": "en-gb:silver",
        "language": "en-gb",
        "name": "silver",
        "resource": "en_gb_silver.g2lex",
        "kind": "pronunciation",
        "rating": 3,
        "case_aliases": True,
        "phoneme_encoding": "kokoro-v1",
        "default_priority": 20,
    },
    {
        "id": "sv-se:nst",
        "language": "sv-se",
        "name": "nst",
        "resource": "sv_nst.g2lex",
        "kind": "pronunciation",
        "case_aliases": False,
        "phoneme_encoding": "ipa",
        "provider": "Joakim/kokoro-sv-g2p",
        "revision": "d19dd10",
        "source_url": "https://huggingface.co/Joakim/kokoro-sv-g2p/blob/d19dd10/g2p/lexicon.tsv",
        "license_expression": "Apache-2.0",
        "license_url": "https://www.apache.org/licenses/LICENSE-2.0",
        "attribution": "Joakim; NST Swedish pronunciation lexicon published in kokoro-sv-g2p",  # noqa: E501
    },
    {
        "id": "fr-fr:gold",
        "language": "fr-fr",
        "name": "gold",
        "resource": "fr_gold.g2lex",
        "kind": "pronunciation",
        "rating": 4,
        "case_aliases": True,
        "phoneme_encoding": "kokoro-v1",
        "default_priority": 10,
    },
    {
        "id": "ja-jp:words",
        "language": "ja-jp",
        "name": "words",
        "resource": "ja_words.g2lex",
        "kind": "membership",
        "case_aliases": False,
        "phoneme_encoding": "none",
        "default_priority": 10,
    },
)
