"""Generated from lexicons/manifest.toml; do not edit manually."""

from __future__ import annotations

GENERATED_LEXICONS = (
    {
        "id": "en-us:gold",
        "language": "en-us",
        "name": "gold",
        "resource": "en_us_gold.g2lex",
        "kind": "pronunciation",
        "rating": 4,
        "case_aliases": True,
        "phoneme_encoding": "kokoro-v1",
        "default_priority": 10,
    },
    {
        "id": "en-us:silver",
        "language": "en-us",
        "name": "silver",
        "resource": "en_us_silver.g2lex",
        "kind": "pronunciation",
        "rating": 3,
        "case_aliases": True,
        "phoneme_encoding": "kokoro-v1",
        "default_priority": 20,
    },
    {
        "id": "en-gb:gold",
        "language": "en-gb",
        "name": "gold",
        "resource": "en_gb_gold.g2lex",
        "kind": "pronunciation",
        "rating": 4,
        "case_aliases": True,
        "phoneme_encoding": "kokoro-v1",
        "default_priority": 10,
    },
    {
        "id": "en-gb:silver",
        "language": "en-gb",
        "name": "silver",
        "resource": "en_gb_silver.g2lex",
        "kind": "pronunciation",
        "rating": 3,
        "case_aliases": True,
        "phoneme_encoding": "kokoro-v1",
        "default_priority": 20,
    },
    {
        "id": "fr-fr:gold",
        "language": "fr-fr",
        "name": "gold",
        "resource": "fr_gold.g2lex",
        "kind": "pronunciation",
        "rating": 4,
        "case_aliases": True,
        "phoneme_encoding": "kokoro-v1",
        "default_priority": 10,
    },
)
