"""Generated from lexicons/manifest.toml; do not edit manually."""

from __future__ import annotations

GENERATED_LEXICONS = (
    {
        "id": "en-us:gold",
        "language": "en-us",
        "name": "gold",
        "resource": "en_us_gold.g2lex",
        "kind": "pronunciation",
        "rating": 4,
        "case_aliases": True,
        "phoneme_encoding": "kokoro-v1",
        "default_priority": 10,
    },
    {
        "id": "en-us:silver",
        "language": "en-us",
        "name": "silver",
        "resource": "en_us_silver.g2lex",
        "kind": "pronunciation",
        "rating": 3,
        "case_aliases": True,
        "phoneme_encoding": "kokoro-v1",
        "default_priority": 20,
    },
    {
        "id": "en-gb:gold",
        "language": "en-gb",
        "name": "gold",
        "resource": "en_gb_gold.g2lex",
        "kind": "pronunciation",
        "rating": 4,
        "case_aliases": True,
        "phoneme_encoding": "kokoro-v1",
        "default_priority": 10,
    },
    {
        "id": "en-gb:silver",
        "language": "en-gb",
        "name": "silver",
        "resource": "en_gb_silver.g2lex",
        "kind": "pronunciation",
        "rating": 3,
        "case_aliases": True,
        "phoneme_encoding": "kokoro-v1",
        "default_priority": 20,
    },
    {
        "id": "de-de:gold",
        "language": "de-de",
        "name": "gold",
        "resource": "de_gold.g2lex",
        "kind": "pronunciation",
        "rating": 4,
        "case_aliases": False,
        "phoneme_encoding": "ipa",
        "default_priority": 10,
    },
    {
        "id": "de-de:crane",
        "language": "de-de",
        "name": "crane",
        "resource": "de_crane.g2lex",
        "kind": "pronunciation",
        "case_aliases": False,
        "phoneme_encoding": "ipa",
        "provider": "crane-local-ai",
        "revision": "bfd51698069a30e1b20bbf54479b55af50b4161d",
        "source_url": "https://huggingface.co/datasets/crane-local-ai/g2p-lexicons/blob/bfd51698069a30e1b20bbf54479b55af50b4161d/de/de.tsv",
        "license_expression": "CC-BY-SA-4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0/",
        "attribution": "German Wiktionary contributors; dataset extraction/publishing by Crane Local AI",  # noqa: E501
    },
    {
        "id": "fr-fr:gold",
        "language": "fr-fr",
        "name": "gold",
        "resource": "fr_gold.g2lex",
        "kind": "pronunciation",
        "rating": 4,
        "case_aliases": True,
        "phoneme_encoding": "kokoro-v1",
        "default_priority": 10,
    },
    {
        "id": "ja-jp:words",
        "language": "ja-jp",
        "name": "words",
        "resource": "ja_words.g2lex",
        "kind": "membership",
        "case_aliases": False,
        "phoneme_encoding": "none",
        "default_priority": 10,
    },
)
